name: SwiftHero
favicon: null
layout_spectrum: 0.12542
typography_spectrum: 0.59386
title: Building a better app experience through Swift.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71994802-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
